### ISSUE TITLE
API or Authentication broken?

### ISSUE THREAD

**Issue by dthorndyke** [dustindclark/homebridge-rinnai-controlr#17] opened 2023-01-16 23:43 UTC
**Describe The Bug:**
No longer able to authenticate with the Rinnai api.

The plugin has been working great for the last few months we have been using it. Today, I noticed the recirculation was no longer being triggered from our motion sensors. Investigating in homebridge logs showed an issue authenticating. Even though the error says “incorrect username or password”, I verified this is not the case by logging in with the same credentials vai the Control-R app. (Besides things have been working for months without any changes to my system.) Further tried restarting Homebridge, rebooting the device, uninstalling and reinstalling the plugin. Same results and same error log every time.

I assume the Control-R api has been changed in some way or the API_KEY hard-coded within the plugin’s constants file needs to be updated, but I’m not quite clear on how to debug the plugin on my end.

**To Reproduce:**
Install the plugin.
Configure with your credentials.
Restart Homebridge and check your logs.
Try to control your water heater from Homebridge or Homekit.

**Expected behavior:**
Authentication does not fail when correct credentials are provided.
Perhaps more precise error logs depending on the root cause of the issue.

**Logs:**

```
Caught error authenticating. NotAuthorizedException: Incorrect username or password.
at /usr/lib/node modules/homebridge-rinnai-controlr/node modules/amazon-cognito-identity-j s/lib/Client.js:129:19
at processticksAndRejections (node: internal/process/task queues: 96:5) {
code:
"NotAuthorizedException'
```

**Plugin Config:**

```json
{
    "username": "xxxx",
    "password": "xxxx",
    "recirculationDuration": 15,
    "temperatureUnits": "F",
    "minimumTemperature": 120,
    "maximumTemperature": 140,
    "platform": "RinnaiControlR",
    "name": "Rinnai"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.25
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.14.2
* **NPM Version**: 8.5.0
* **Operating System**: Raspbian

**Comment by dustindclark** [comment] 2023-01-17 00:05
Rinnai recently turned on auth. Make sure you're on the latest version of the plugin. Otherwise, it has to be either an incorrect username or password configured.DustinSent from my iPhoneOn Jan 16, 2023, at 5:43 PM, dthorndyke ***@***.***> wrote:﻿

Describe The Bug:
No longer able to authenticate with the Rinnai api.
The plugin has been working great for the last few months we have been using it. Today, I noticed the recirculation was no longer being triggered from our motion sensors. Investigating in homebridge logs showed an issue authenticating. Even though the error says “incorrect username or password”, I verified this is not the case by logging in with the same credentials vai the Control-R app. (Besides things have been working for months without any changes to my system.) Further tried restarting Homebridge, rebooting the device, uninstalling and reinstalling the plugin. Same results and same error log every time.
I assume the Control-R api has been changed in some way or the API_KEY hard-coded within the plugin’s constants file needs to be updated, but I’m not quite clear on how to debug the plugin on my end.
To Reproduce:
Install the plugin.
Configure with your credentials.
Restart Homebridge and check your logs.
Try to control your water heater from Homebridge or Homekit.
Expected behavior:
Authentication does not fail when correct credentials are provided.
Perhaps more precise error logs depending on the root cause of the issue.
Logs:
Caught error authenticating. NotAuthorizedException: Incorrect username or password.
at /usr/lib/node modules/homebridge-rinnai-controlr/node modules/amazon-cognito-identity-j s/lib/Client.js:129:19
at processticksAndRejections (node: internal/process/task queues: 96:5) {
code:
"NotAuthorizedException'

Plugin Config:
{
    "username": "xxxx",
    "password": "xxxx",
    "recirculationDuration": 15,
    "temperatureUnits": "F",
    "minimumTemperature": 120,
    "maximumTemperature": 140,
    "platform": "RinnaiControlR",
    "name": "Rinnai"
}
Screenshots:

Environment:

Plugin Version: 1.0.25
Homebridge Version: 1.6.0
Node.js Version: 16.14.2
NPM Version: 8.5.0
Operating System: Raspbian

**Comment by dthorndyke** [comment] 2023-01-18 01:26
Thanks for the quick reply @dustindclark. Could you share what you mean by “Rinnai recently turned on auth”?

I wasn’t able to resolve this issue, so I set up a new Homebridge instance on another machine. I was able to get the Rinnai plugin running there without the same authentication errors popping up in the logs. It can read status details from my water heater, but when issuing the command to turn on the recirculation pump, I see there is a “400 Bad Response” in the logs. The pump does not activate this way. I am still able to turn on the pump via the ControlR app. Any suggestions where to look for the cause of the failure? Thanks!
```
[1/17/2023, 5:08:21 PM] [Rinnai] Temperature Slider Min: 48.888888888888886, Max: 60, current temperature: 54.44444444444444
[1/17/2023, 5:08:21 PM [Rinnai] Device AC000W010685414 has recirculation capabilities. Adding service
[1/17/2023, 5:08:21 PM [Rinnai] Polled 1 Rinnai devices successfully.
[1/17/2023, 5:08:24 PM [Rinnai] setRecirculatective to true for device AC000W010685414
[1/17/2023, 5:08:24 PM [Rinnai] Sending state to Rinnai. Endpoint: https://698suy42s3.execute-api.us-east-1.amazonaws.com/Prod/thing/CR 342552£4-1bb0-4d30-a139-56706a50c2a/shadow Re quest: {"method": "patch", "body":"{\"set priority status\":true, \"recirculation duration\":\"15" "set recirculation enabled\":true)", "headers": ("User-Agent": "okhttp/3.12.1", "Content-Type" : "application/x-www-form-urlencoded", "Accept-Encoding": "gzip", "Accept": "application/ json, text /plain, */*", "Authorization": "Bearer XXXXX"}}
[1/17/2023, 5:08:24 PM [Rinnai] Set state responded with 400 Bad Request. Body: <}
```

**Comment by dustindclark** [comment] 2023-01-18 11:07
Rinnai's API wasn't previously secured. This means that anyone with your email address could control your water heater, but it also means that this plugin would work even with an incorrect password.

The only other thing to check is your Ctrl-R firmware and app. The old version will not work. Check that you're on the latest (see attached).

I know the latest plugin version works because I actively use it, so there has to be something different with your setup or [configuration.

![IMG_0308](https://user-images.githubusercontent.com/3819936/213156213-396d7863-27f1-4371-bdcf-4480e16c9bdd.PNG)

**Comment by dthorndyke** [comment] 2023-01-19 00:13
Gotcha, ok thanks for the context.

I just tried the following based on what you mentioned:
- Confirmed the app and firmware versions
- The plugin version I have installed is listed as `1.0.25`
- I signed out of the iOS ControlR app, signed back in with the credentials stored in my 1Password.
- Copied those same credentials from 1Password into the plugin config for username and password.
- Restarted Homebridge with debug mode enabled. The logs show the plugin is able to poll my water heater.
- Attempting to turn on the recirculation from Homebridge or Homekit does not work, and the logs show `set state responded with 400 bad request`
- By the way, the ControlR app on the iOS store v2.5.7 was lasted updated 10 months ago.
- Also, I have rebooted my water heater, modem, router, and homebridge device.

Anything else you can think for me to check? 

## Screenshots
![IMG_2025](https://user-images.githubusercontent.com/2053902/213325050-37c2d878-89b4-42af-8ad3-b696991ce950.jpeg)

![IMG_1645](https://user-images.githubusercontent.com/2053902/213325067-84cf78f5-bedc-41ae-a000-5122e26e3365.jpeg)

![IMG_1646](https://user-images.githubusercontent.com/2053902/213325084-18553c4e-2063-4daf-9826-f12c13c3ccb5.jpeg)

![IMG_2026](https://user-images.githubusercontent.com/2053902/213325138-3e2dc56c-84a2-4c5f-a7cf-c6c57ae83814.jpeg)

**Comment by dustindclark** [comment] 2023-01-20 14:38
I'm going to close this one in favor of #16 such that we can consolidate/continue the discussion there.

**Closed by dustindclark** 2023-01-20 14:38 UTC
Labels: bug
